// PORT=8000
// MONGO_URI=mongodb+srv://rutukoladiya:suMita393@task1.hbjjerf.mongodb.net
// CORS_ORIGIN=*
// ACCESS_TOKEN_SECRET_KEY=nannamunharahihu
// ACCESS_TOKEN_EXPIRY=1d
// REFRESH_TOKEN_SECRET_KEY=deshkasipahihu
// REFRESH_TOKEN_EXPIRY=10d

// CLOUDINARY_CLOUD_NAME=
// CLOUDINARY_API_KEY=
// CLOUDINARY_API_SECRET=
