import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-gray-100 text-gray-700 flex justify-between px-20 py-4">
          <h1>Next.js Dashboard</h1>
          <nav className="flex gap-8 items-center">
            <Link className="hover:text-red-800" href="/">
              Home
            </Link>
            <Link className="hover:text-red-800" href="/ssr">
              SSR
            </Link>
            <Link className="hover:text-red-800" href="/ssg">
              SSG
            </Link>
            <Link className="hover:text-red-800" href="/isr">
              ISR
            </Link>
            <Link className="hover:text-red-800" href="/mix">
              MIX
            </Link>
          </nav>
        </header>
        <main style={{ padding: "20px" }}>{children}</main>
      </body>
    </html>
  );
}
