import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header style={{ background: "#333", color: "#fff", padding: "10px" }}>
          {/* <nav style={{ display: "flex", gap: "10px" }}>
            <Link className="text-gray-800" href="/">
              Home
            </Link>
            <Link className="text-gray-800" href="/ssr">
              SSR
            </Link>
            <Link className="text-gray-800" href="/ssg">
              SSG
            </Link>
            <Link className="text-gray-800" href="/isr">
              ISR
            </Link>
          </nav> */}
          <h1>Next.js Dashboard</h1>
        </header>
        <main style={{ padding: "20px" }}>{children}</main>
      </body>
    </html>
  );
}
